#!/usr/bin/env python3
"""Pick a random Lenny article/podcast for daily recommendation."""

import json
import hashlib
import os
import sys
import urllib.request
import urllib.parse
from datetime import datetime, timezone, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_PATH = REPO_ROOT / ".agents/skills/lennys-podcast-newsletter/references/01-start-here/index.json"
REFERENCES_DIR = REPO_ROOT / ".agents/skills/lennys-podcast-newsletter/references"


def load_index():
    with open(INDEX_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def pick_daily_item(index_data):
    """Pick one item deterministically based on today's date."""
    all_items = []
    for podcast in index_data.get("podcasts", []):
        podcast["type"] = "podcast"
        all_items.append(podcast)
    for newsletter in index_data.get("newsletters", []):
        newsletter["type"] = "newsletter"
        all_items.append(newsletter)

    # Use date as seed for deterministic daily pick
    today = datetime.now(timezone(timedelta(hours=8))).strftime("%Y-%m-%d")
    seed = int(hashlib.md5(today.encode()).hexdigest(), 16)
    pick = all_items[seed % len(all_items)]
    return pick, today


def read_content(filename, max_lines=80):
    """Read the beginning of the content file."""
    filepath = REFERENCES_DIR / filename
    if not filepath.exists():
        return "(Content file not found)"
    lines = filepath.read_text(encoding="utf-8").splitlines()
    preview = "\n".join(lines[:max_lines])
    if len(lines) > max_lines:
        preview += f"\n\n... (共 {len(lines)} 行，以上为摘要预览)"
    return preview


def format_issue(item, today, content_preview):
    type_label = "Podcast" if item["type"] == "podcast" else "Newsletter"
    tags = ", ".join(f"`{t}`" for t in item.get("tags", []))
    guest = item.get("guest", "")
    guest_line = f"**Guest:** {guest}\n" if guest else ""

    title = f"Lenny Daily Read [{today}]: {item['title'][:60]}"

    body = f"""## Lenny's {type_label} Daily Recommendation

**Title:** {item['title']}
**Date:** {item.get('date', 'N/A')}
**Type:** {type_label}
{guest_line}**Tags:** {tags}
**Word Count:** {item.get('word_count', 'N/A')}

### Description
{item.get('description', 'N/A')}

### Content Preview
{content_preview}

---
*Auto-generated by Lenny Daily Pick*
"""
    return title, body


def send_wechat(title, body, token):
    """Send notification to WeChat via PushPlus."""
    url = "http://www.pushplus.plus/send"
    # Convert markdown to simple HTML-friendly format
    data = json.dumps({
        "token": token,
        "title": title,
        "content": body,
        "template": "markdown",
    }).encode("utf-8")

    req = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            result = json.loads(resp.read().decode())
            if result.get("code") == 200:
                print(f"WeChat push succeeded: {result.get('msg')}")
            else:
                print(f"WeChat push failed: {result}", file=sys.stderr)
    except Exception as e:
        print(f"WeChat push error: {e}", file=sys.stderr)


def main():
    index_data = load_index()
    item, today = pick_daily_item(index_data)
    content_preview = read_content(item["filename"])
    title, body = format_issue(item, today, content_preview)

    # Output for GitHub Actions
    output_dir = os.environ.get("GITHUB_OUTPUT", "")
    if output_dir:
        with open(output_dir, "a") as f:
            f.write(f"title={title}\n")

        body_file = Path(os.environ.get("RUNNER_TEMP", "/tmp")) / "issue_body.md"
        body_file.write_text(body, encoding="utf-8")
        with open(output_dir, "a") as f:
            f.write(f"body_file={body_file}\n")
    else:
        # Local testing
        print(f"Title: {title}\n")
        print(body)

    # Send to WeChat if token is available
    pushplus_token = os.environ.get("PUSHPLUS_TOKEN", "")
    if pushplus_token:
        send_wechat(title, body, pushplus_token)
    else:
        print("(No PUSHPLUS_TOKEN set, skipping WeChat push)")


if __name__ == "__main__":
    main()
